### ISSUE TITLE
How does carousel logic work?

### ISSUE THREAD

**Issue by WorldsEndless** [BYU-ODH/byu-humanities-department#65]
Which posts show up in the carousel, and how can a department secretary add a post to a carousel?

**Comment by aaroncowley** [comment]
the carousel logic grabs (if i remember correctly) 7 posts from internal storage and 7 from humanities.byu.edu that have that department "tagged" it then bubble sorts these based upon date.  It also has some robustness if one of these links fails or provides a null object.  If a secretary wants to add a post just make sure they make the date the day of posting and it should be put as the first item of the carousel.  It uses the rest api to grab both the external and internal links to the content as the two separate content types did not merge nicely otherwise.
